server:
  port: 9999

spring:
  datasource:
    username: xxx
    password: 'xxx'
    url: jdbc:mysql://localhost:3306/taptap?serverTimezone=UTC&useUnicode=true&charactorEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
